// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicExample: typeof import('./components/BasicExample.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CounterFPS: typeof import('./components/CounterFPS.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    PerformanceExample: typeof import('./components/PerformanceExample.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
